# Generated by Django 2.2.2 on 2019-06-26 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('trans_num', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(choices=[('survey', '填写问卷'), ('morning', '叫早服务'), ('takeout', '带饭服务'), ('express', '代领快递'), ('drug', '代买药品')], max_length=32)),
                ('bonus', models.IntegerField(default='10')),
                ('uploader', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=32)),
                ('detail', models.CharField(max_length=512)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('d_time', models.DateTimeField(auto_now_add=True)),
                ('is_accept', models.BooleanField(default='False')),
                ('acceptor', models.CharField(default='None', max_length=256)),
                ('is_finish', models.BooleanField(default='False')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
                'ordering': ['trans_num'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=32)),
                ('point', models.IntegerField(default='0')),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['c_time'],
            },
        ),
    ]
