# Generated by Django 2.2.2 on 2019-06-15 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20190614_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('trans_num', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(choices=[('survey', '填问卷'), ('morning', '叫早'), ('takeout', '带饭'), ('express', '代领快递'), ('drug', '代买药')], default='填问卷', max_length=32)),
                ('bonus', models.IntegerField(default='10')),
                ('uploader', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=32)),
                ('detail', models.CharField(max_length=256)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('d_time', models.DateTimeField()),
                ('is_accept', models.BooleanField(default='False')),
                ('is_finish', models.BooleanField(default='False')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
                'ordering': ['trans_num'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='point',
            field=models.IntegerField(default='0'),
        ),
    ]
