# Generated by Django 2.2.2 on 2019-06-15 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20190615_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('填写问卷', 'survey'), ('叫早服务', 'morning'), ('带饭服务', 'takeout'), ('代领快递', 'express'), ('代买药品', 'drug')], default='填问卷', max_length=32),
        ),
    ]
