# Generated by Django 2.2.2 on 2019-06-15 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20190615_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('survey', '填问卷'), ('morning', '叫早'), ('takeout', '带饭'), ('express', '代领快递'), ('drug', '代买药')], default='填问卷', max_length=32),
        ),
    ]
