# Generated by Django 2.2.2 on 2019-06-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20190615_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('survey', '填写问卷'), ('morning', '叫早服务'), ('takeout', '带饭服务'), ('express', '代领快递'), ('drug', '代买药品')], default='填问卷', max_length=32),
        ),
    ]
