# Generated by Django 2.2.2 on 2019-06-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_auto_20190615_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='d_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
