# Generated by Django 2.2.2 on 2019-06-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_auto_20190615_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='detail',
            field=models.CharField(max_length=512),
        ),
    ]
