# Generated by Django 2.2.2 on 2019-06-15 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_auto_20190615_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='accepter',
            field=models.CharField(default='None', max_length=256),
        ),
    ]
